import { mkdtempSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import {
  openVerifiedRegularFileNoFollow,
  verifyOpenedRegularFileSync,
} from "../fs-read.js";
import { MAX_NATIVE_IMAGE_BYTES } from "../vision.js";
import { registerTool } from "./registry.js";

const MAX_HINT_CHARS = 2_000;

function isWithin(root: string, target: string): boolean {
  const rel = relative(root, target);
  return rel === "" || (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel));
}

function mediaTypeFromBytes(bytes: Uint8Array): { mediaType: string; extension: string } | null {
  if (
    bytes.length >= 8
    && bytes[0] === 0x89
    && Buffer.from(bytes.subarray(1, 4)).toString("ascii") === "PNG"
    && bytes[4] === 0x0d
    && bytes[5] === 0x0a
    && bytes[6] === 0x1a
    && bytes[7] === 0x0a
  ) return { mediaType: "image/png", extension: ".png" };
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return { mediaType: "image/jpeg", extension: ".jpg" };
  }
  const signature = Buffer.from(bytes.subarray(0, 6)).toString("ascii");
  if (signature === "GIF87a" || signature === "GIF89a") {
    return { mediaType: "image/gif", extension: ".gif" };
  }
  if (
    bytes.length >= 12
    && Buffer.from(bytes.subarray(0, 4)).toString("ascii") === "RIFF"
    && Buffer.from(bytes.subarray(8, 12)).toString("ascii") === "WEBP"
  ) return { mediaType: "image/webp", extension: ".webp" };
  return null;
}

async function readVerifiedWorkspaceImage(
  rawPath: string,
  cwd: string,
): Promise<{ bytes: Buffer; mediaType: string; extension: string }> {
  const requested = isAbsolute(rawPath) ? resolve(rawPath) : resolve(cwd, rawPath);
  const root = resolve(cwd);
  const verified = await openVerifiedRegularFileNoFollow(requested, {
    action: "inspect image",
    rejectHardLinks: true,
    protectSensitive: true,
  });
  try {
    const canonicalRoot = realpathSync.native(root);
    if (!isWithin(canonicalRoot, verified.canonicalPath)) {
      throw new Error("image must be a regular file inside the current workspace");
    }
    if (verified.info.size <= 0) throw new Error("image is empty");
    if (verified.info.size > MAX_NATIVE_IMAGE_BYTES) {
      throw new Error(
        `image is ${verified.info.size} bytes; the safe image limit is ${MAX_NATIVE_IMAGE_BYTES} bytes`,
      );
    }
    const bytes = Buffer.allocUnsafe(verified.info.size);
    let offset = 0;
    while (offset < bytes.length) {
      const { bytesRead } = await verified.handle.read(bytes, offset, bytes.length - offset, offset);
      if (!bytesRead) throw new Error("image ended before its declared size");
      offset += bytesRead;
    }
    const latest = await verified.handle.stat();
    verifyOpenedRegularFileSync(requested, latest, {
      action: "inspect image",
      rejectHardLinks: true,
      protectSensitive: true,
    });
    if (
      latest.dev !== verified.info.dev
      || latest.ino !== verified.info.ino
      || latest.size !== verified.info.size
      || latest.mtimeMs !== verified.info.mtimeMs
      || latest.ctimeMs !== verified.info.ctimeMs
    ) throw new Error("image changed while it was being read");
    const detected = mediaTypeFromBytes(bytes);
    if (!detected) throw new Error("only valid PNG, JPEG, GIF, and WebP images are supported");
    return { bytes, ...detected };
  } finally {
    await verified.handle.close().catch(() => {});
  }
}

registerTool({
  name: "inspect_image",
  description:
    "Inspect a PNG, JPEG, GIF, or WebP image that already exists inside the current workspace, including " +
    "an image downloaded or generated by another tool during this task. Uses the current session's authorized " +
    "image-capable model (or its authorized compatibility helper) and returns a factual visual description. " +
    "Use this instead of read_file, shell OCR scripts, or reading API keys when you need to see a local image.",
  input_schema: {
    type: "object",
    properties: {
      path: { type: "string", description: "Image path inside the current workspace" },
      focus: {
        type: "string",
        description: "Optional visual question or detail to focus on, such as transcribing a form or reading a chart",
      },
    },
    required: ["path"],
  },
  kind: "read",
  concurrencySafe: false,
  requiresProjectWorkspace: true,
  async run(input, ctx) {
    if (typeof input.path !== "string" || !input.path.trim()) {
      return "Error: inspect_image `path` must be a non-empty string.";
    }
    if (!ctx.inspectImage) {
      return (
        "Error: this run has no authorized image inspection route. Switch the current conversation to an " +
        "image-capable model or configure an image compatibility helper for this same connection; do not read .env or API keys."
      );
    }
    const focus = typeof input.focus === "string"
      ? input.focus.replace(/\r\n?/g, "\n").trim().slice(0, MAX_HINT_CHARS)
      : undefined;
    let tempRoot: string | undefined;
    try {
      const snapshot = await readVerifiedWorkspaceImage(input.path, ctx.cwd);
      tempRoot = mkdtempSync(join(tmpdir(), "hara-inspect-image-"));
      const snapshotPath = join(tempRoot, `snapshot${snapshot.extension}`);
      writeFileSync(snapshotPath, snapshot.bytes, { flag: "wx", mode: 0o600 });
      const result = await ctx.inspectImage(
        { path: snapshotPath, mediaType: snapshot.mediaType },
        focus,
        ctx.signal,
      );
      const text = result.text.trim();
      if (!text) return "Error: the authorized image model returned an empty description.";
      return (
        `Image inspected with ${result.model} (${snapshot.mediaType}, ${snapshot.bytes.length} bytes).\n` +
        text
      );
    } catch (error) {
      return `Error: cannot inspect image: ${error instanceof Error ? error.message : String(error)}`;
    } finally {
      if (tempRoot) rmSync(tempRoot, { recursive: true, force: true });
    }
  },
});
